sudo: false
# dist: trusty

# sudo: required
# dist: trusty
# group: deprecated-2017Q4


language: python

python:
  - 2.7

branches:
  only:
    - master

env:
   
before_install:
  - df -h
  - free
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda config --add channels conda-forge
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv pip pytest
#  - conda install -n testenv numpy
#  - conda install -n testenv scipy
#  - conda install -n testenv matplotlib
  - conda install -n testenv mpi4py

script:
  - source activate testenv
#  - python -c "import scipy"
  - mpirun -np 2 python -c "from mpi4py.MPI import COMM_WORLD as w; print w.Get_rank()"

notifications:
  email:
    on_success: change
    on_failure: always
